baseURL = "https://topre.dev/"
languageCode = "en-us"
title = "topre.dev"
theme = "kross-hugo"


# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.main]]
URL = "about"
name = "About"
weight = 1


[[menu.main]]
URL = "contact"
name = "Contact"
weight = 2


# default parameters
[params]
home = "Home"
logo = "/images/logo/logowhitecrop.png"
# theme color
theme_color = "#000744"
# contact info
phone = "+61 427 475 077"
email = "hello@topre.dev"
address = "102 Victoria St Carlton Vic 3053"
# meta description
author = "topre.dev"
description = "Simply designed sites"
# google analytics
google_analytics_id = "UA-38731586-8" # Your ID
# copyright
copyright = "Copyright &copy; 2020 topre.dev"


# preloader
[params.preloader]
enable = true
preloader = "png" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = true
form_action = "https://formspree.io/xdowpdwg" # contact form works with : https://formspree.io
